language: node_js
node_js:
  - "12.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://github.com/lightcraf/angular-tvmaze
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ed0dc16362c144e179e3eb7f023a7ce0b40a4979
  keep_history: true
  on:
    branch: master